CREATE TABLE IF NOT EXISTS task(
	id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	description VARCHAR(100),
    status VARCHAR(1) NOT NULL,
    deadline TIMESTAMP,

	PRIMARY KEY(id)
);
