package jp.co.software.excite.training.infrastructure.mapper;

import java.util.List;
import jp.co.software.excite.training.infrastructure.entity.Task;
import jp.co.software.excite.training.infrastructure.entity.TaskExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Fri Jan 12 16:51:05 JST 2024
     */
    long countByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Fri Jan 12 16:51:05 JST 2024
     */
    int deleteByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Fri Jan 12 16:51:05 JST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Fri Jan 12 16:51:05 JST 2024
     */
    int insert(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Fri Jan 12 16:51:05 JST 2024
     */
    int insertSelective(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Fri Jan 12 16:51:05 JST 2024
     */
    List<Task> selectByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Fri Jan 12 16:51:05 JST 2024
     */
    Task selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Fri Jan 12 16:51:05 JST 2024
     */
    int updateByExampleSelective(@Param("row") Task row, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Fri Jan 12 16:51:05 JST 2024
     */
    int updateByExample(@Param("row") Task row, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Fri Jan 12 16:51:05 JST 2024
     */
    int updateByPrimaryKeySelective(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK
     *
     * @mbg.generated Fri Jan 12 16:51:05 JST 2024
     */
    int updateByPrimaryKey(Task row);
}